import type { Metadata } from "next";
import { Figtree, Intel_One_Mono } from "next/font/google";
import "./globals.css";

const figtree = Figtree({
  variable: "--font-figtree",
  subsets: ["latin"],
});

const intelOneMono = Intel_One_Mono({
  variable: "--font-intel-one-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${figtree.variable} ${intelOneMono.variable} h-full min-h-full antialiased`}
    >
      <body className="h-full min-h-full flex flex-col">{children}</body>
    </html>
  );
}
